### ISSUE TITLE
bug: Uncaught TypeError: Failed to resolve module specifier 

### ISSUE THREAD

**Issue by Bisstocuz** [jspm/vite-plugin-jspm#11]
> Uncaught TypeError: Failed to resolve module specifier "vite/preload-helper". Relative references must start with either "/", "./", or "../".

steps:
1. pnpm build
2. pnpm preview

environment: (a Vue 3 + Vite 4 project)
[demo.zip](https://github.com/jspm/vite-plugin-jspm/files/12238139/demo.zip)

**Comment by Bisstocuz** [comment]
I don't know why `import-map` is empty:
```html
<script type="importmap">{}</script>
```

**Comment by JayaKrishnaNamburu** [comment]
@Bisstocuz a new version of `v0.5` is also released with the new `@jspm/generator` and the two fixes #10 #11
Please let me know if the fix is still not working
