### ISSUE TITLE
Dependencies need to be updated

### ISSUE THREAD

**Issue by Bisstocuz** [jspm/vite-plugin-jspm#8]
I‘m using TypeScript and Vite 4 + Vue 3, I tried this plugin, it's necessary to install `@jspm/generator` at the same time if I wanna implement my custom providers.

But I can only install `@jspm/generator` v1.1.1, otherwise, TypeScript will throw a warning.

**Comment by JayaKrishnaNamburu** [comment]
Thanks for reporting, i will take a look 👍
